name: Deployment
on: push
jobs:
    linting:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Install dependencies
            run: npm ci
          - name: Lint codebase
            run: npm run lint
    testing:
      needs: linting
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Install dependencies
            run: npm ci
          - name: Test code
            run: npm run test
    deployment:
      needs: testing
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Install dependencies
            run: npm ci
          - name: Build code
            run: npm run build
          - name: Deploy code
            run: echo "Deploying code..."
